### PR TITLE
Add axel play to reel holder.

### PR DESCRIPTION
**Pull request by scott-t-wilson**
Fix for issue #1.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @scott-t-wilson 

great to see somebody is not afraid to dig through that huge spaghetti code ;-)

You spotted an inconsistency. However, there are some rules "in play" here (pun intended) :-)

1. The play is always applied to the smaller part, so if it needs to be tuned, it is faster to reprint. Therefore, the play should be applied to the counter axle:
    Counter Axle
    Here in the code:
    https://github.com/markmaker/PushPullFeeder/blob/37d01af7cad5113ebe345ad86df1fe50f7c4d943/PushPullFeeder.scad#L1732-L1736
   As you see in this code, the counter-axle currently conical. The farther you press it in, the stronger it connects. This is how I initially designed it. I completely forgot about this and you are right that this is inconsistent. I have since changed everything else to non-conical to allow for part replacement and this one should be changed too. 

2. When the axle does not need to rotate in operation, i.e. is only used to snap things together, the `play` rather than the `axle_play` is used:
    axle_play

So this should be changed to:
```
                        // counter axle
                        translate([reel_x, reel_y, e]) 
                            cylinder_p(d=reel_axle-2*reel_axle_wall-**play**-phase2_play, 
                                h=spool_axle_groove_z-e);
```

Could you revert your changes, instead do these, commit and push to the same branch? I can then merge your PR. Big thanks!

_Mark

**Comment by scott-t-wilson** [comment]
I actually knew that about axel play at some point, but when I got around to looking at the code I remembered it backwards.

With my printer I'm actually using the 'play' variable too, without it the parts won't separate without breaking. For reference I'm using 0.02 for axel_play, and -0.02 for play. Well within your expected tolerances I think.

Thanks for the explanation and response, I'll make the changes and resubmit.

**Comment by markmaker** [comment]
> Well within your expected tolerances I think.

Yes, these are probably even the best values possible. 

Thanks, Scott.

_Mark

**Comment by scott-t-wilson** [comment]
I'm going to submit an entirely new PR, I wasn't able to figure out how to remove the original incorrect commit other than more commits. Probably pointless, but once I started down that path...

**Pull request closed without merging**
